# Generated by Django 5.2.5 on 2025-08-26 23:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('grupo_muscular', models.CharField(blank=True, max_length=80)),
                ('equipamento', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracao_meses', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('altura_m', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.5)])),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='website.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.plano'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cref', models.CharField(max_length=30, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('modalidades', models.ManyToManyField(blank=True, related_name='professores', to='website.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='website.aluno')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('capacidade', models.PositiveIntegerField(default=15)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('dias_semana', models.CharField(help_text='Ex.: 2ª/4ª/6ª 07:00', max_length=40)),
                ('ativa', models.BooleanField(default=True)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='website.modalidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='website.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='website.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='website.turma')),
            ],
            options={
                'unique_together': {('aluno', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Ex.: 2025-08 (competência)', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('pago', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='website.aluno')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.plano')),
            ],
            options={
                'unique_together': {('aluno', 'referencia')},
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='website.matricula')),
            ],
            options={
                'unique_together': {('matricula', 'data')},
            },
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('repeticoes', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('carga_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('descanso_seg', models.PositiveIntegerField(default=60)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='website.treino')),
            ],
            options={
                'unique_together': {('treino', 'exercicio')},
            },
        ),
    ]
